Add vulnerability guidance to risk to self
ministryofjustice/hmpps-community-accommodation-tier-2-ui pull request #671
Opened 2024-04-29 12:38 UTC by chaneldiepmoj

# Context
Add new vulnerability guidance in the risk to self section.

[Jira ticket 347](https://dsdmoj.atlassian.net/browse/CAS2-347)

# Changes in this PR

### Before
![Screenshot 2024-04-29 at 13 33 41](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/assets/150680734/0ff4a68e-d9b6-4b62-8937-f52570e8c190)

### After
![Screenshot 2024-04-29 at 13 37 11](https://github.com/ministryofjustice/hmpps-community-accommodation-tier-2-ui/assets/150680734/cd073a40-78c8-4e64-9355-3b2ab8ff360c)

# Release checklist

As part of our continuous deployment strategy we must ensure that this work is
ready to be released at any point. Before merging to `main` we must first
confirm:

## Pre merge checklist

- [ ] Are any changes required to the e2e tests?
- [ ] If you've added a new route, have you added a new
  `auditEvent`? (see `server/routes/apply.ts` for examples)
- [ ] Are there environment variables or other infrastructure configuration which needs to be included in this release?
- [ ] Are there any data migrations required. Automatic or manual?
- [ ] Does this rely on changes being deployed to the CAS API?

## Post merge checklist

Once we've merged it will be auto-deployed to the dev environment.

[Find the build-and-deploy job in CircleCI](https://app.circleci.com/pipelines/github/ministryofjustice/hmpps-community-accommodation-tier-2-ui).

Should a release fail at any step, you as the author should now lead the work to
fix it as soon as possible.

2024-04-29 13:25 UTC, patrickjfl requested changes
Couple of minor things, but otherwise looks great!

2024-04-29 13:25 UTC, patrickjfl commented on server/views/applications/pages/risk-to-self/vulnerability.njk
> +    </p>
can you stick in a closing tag for the `<ul>` above the `<p>` tag here? As it stands, because the list isn't closed, the rest of the text is formatting as if it's a list 🙂

2024-04-29 13:25 UTC, patrickjfl commented on server/views/applications/pages/risk-to-self/vulnerability.njk
> +      <li>modern day slavery, such as forced labour and sexual or criminal exploitation</li>
are you content without a full stop at the end of the final bullet point?

2024-04-29 14:23 UTC, chaneldiepmoj commented on server/views/applications/pages/risk-to-self/vulnerability.njk
> +      <li>modern day slavery, such as forced labour and sexual or criminal exploitation</li>
Yes all good, as per [Bullet points and steps section in the GOV.UK style guide](https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style):

> there is no full stop after the last bullet

Thanks for checking :)

2024-04-30 14:37 UTC, patrickjfl approved these changes

2024-04-30 14:50 UTC, merged